# Generated by Django 5.2.7 on 2025-10-22 10:32

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('statut', models.CharField(choices=[('collaborator', 'Collaborateur'), ('associate', 'Associé'), ('senior', 'Sénior'), ('admin', 'Administrateur')], max_length=20, verbose_name='Statut')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=account.models.signature_path, verbose_name='Signature')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date ajoutée')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.departement', verbose_name='Département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
