# Generated by Django 5.2.7 on 2025-10-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_added'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
