# Generated by Django 5.2.7 on 2025-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departement',
            field=models.CharField(choices=[('', '--'), ('audit', 'Audit'), ('tax', 'Fiscalité'), ('accounting', 'Comptabilité'), ('advisory', 'Conseil'), ('other', 'Autres')], default=1, max_length=20, verbose_name='Département'),
            preserve_default=False,
        ),
    ]
