# Generated by Django 5.2.7 on 2025-10-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_departement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='statut',
            new_name='status',
        ),
    ]
