# Generated by Django 5.2.7 on 2025-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email contact')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone contact')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nom de la société')),
                ('raison_sociale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison sociale')),
                ('ninea', models.CharField(blank=True, max_length=100, null=True, verbose_name='NINEA')),
                ('rccm', models.CharField(blank=True, max_length=100, null=True, verbose_name='RCCM')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date ajoutée')),
            ],
        ),
    ]
