# Generated by Django 5.2.7 on 2025-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptationaudit',
            name='question_83',
            field=models.CharField(blank=True, choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Question 83'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='response_83',
            field=models.TextField(blank=True, verbose_name='Réponse 83'),
        ),
    ]
