# Generated by Django 5.2.7 on 2025-10-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acceptationaudit_question_83_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_audit_done_by', to=settings.AUTH_USER_MODEL, verbose_name='Fait par'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_audit_reviewed_by', to=settings.AUTH_USER_MODEL, verbose_name='Revu par'),
        ),
        migrations.AlterField(
            model_name='branche',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_branches', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_managers', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AlterField(
            model_name='sharehol',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_shareholders', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
    ]
