# Generated by Django 5.2.7 on 2025-10-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_acceptationaudit_done_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='business_description',
            field=models.TextField(blank=True, verbose_name="Décrire la nature des activités et la taille de l'entité (par exemple secteur d'activité, produits ou services, principaux clients, principaux fournisseurs)"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='countries_operated',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pays dans lesquels opère l’entité'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='is_eip',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name='EIP (O/N)'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, verbose_name="Forme juridique (de l'entité)"),
        ),
    ]
