# Generated by Django 5.2.7 on 2025-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_acceptationaudit_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='business_description',
            field=models.TextField(verbose_name="Décrire la nature des activités et la taille de l'entité (par exemple secteur d'activité, produits ou services, principaux clients, principaux fournisseurs)"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='closing_date',
            field=models.DateField(verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='countries_operated',
            field=models.CharField(max_length=255, verbose_name="Pays dans lesquels opère l'entité"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Nom du groupe'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='has_cocac',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name="S'agit -il d'un Co-CAC ? si oui indiquer le nom du co-CAC"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='has_independent_review',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name='Le dossier répond-il aux critères de la revue indépendante ? Si oui le(s)quel(s)'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='is_component_audit',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name="S'agit-il de l'audit d'un composant ? si oui nom de l'auditeur du groupe"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='legal_form',
            field=models.CharField(max_length=255, verbose_name="Forme juridique (de l'entité)"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_1',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Les honoraires envisagés représentent-ils une part significative des honoraires du signataire (honoraires égaux ou supérieurs à 15% du CA du signataire) ? Si oui indiquer ci-contre les mesures de sauvegarde prévues.'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_10',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="L'acceptation de cette mission peut-elle compromettre notre relation avec nos clients existants ? Par exemple, un des concurrents de ce client est-il client chez nous et ceci menace-t-il notre indépendance ? Si OUI, préciser ci-contre si vous obtenu le consentement écrit des deux clients."),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_11',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Existe-t-il des relations d'affaires avec le client ou sa direction pouvant constituer une menace pour l'indépendance?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_12',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="A-t-on connaissance de liens familiaux entre, d'une part, une personne occupant une fonction sensible  au sein de l'entité contrôlée et, d'autre part, le commissaire aux comptes, l'un des membres de l'équipe de contrôle, l'un des membres de la direction du cabinet ou l'un des associés du cabinet ou leurs familles ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_13',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="A-t-on connaissance de liens personnels autres que familiaux entre, d'une part, l'entité contrôlée ou une personne y occupant une fonction sensible et, d'autre part, le commissaire aux comptes ou l'un des membres de la direction du cabinet ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_14',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Existe-t-il un litige opposant au client le cabinet, et susceptible d'affecter notre indépendance ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_15',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='A-t-on procédé aux vérifications requises dans COPERNICUS ? Joindre les preuves '),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_16',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Si l'entité ou l'une de ses parties liées disposent d'opérations à l'international et si/ou elle est cotée ou EIP a-t-on effectué network conflict checking ? Joindre les preuves"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_17',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Après avoir pris connaissance des prestations de service rendues antérieurement par le cabinet ou par son réseau au client, ou à une entité contrôlée par celle-ci ou qui la contrôle, y a-t-il un risque d'auto révision pouvant en découler ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_18',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='A-t-on procédé au domestic check ? Joindre les preuves'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_19',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Le cabinet, les membres du réseau (notamment le réseau Moore, OPTESIS Guinée et Côte d'Ivoire) ont-ils réalisé en faveur du client ou des entités qui la contrôle ou qu'elle contrôle, des prestations incompatibles avec le mandat de CAC ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_2',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Nos honoraires sont-ils insuffisants pour nous permettre d'effectuer notre travail conformément aux normes ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_20',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Sommes-nous dans l'un des cas d'interdiction mentionnés dans les articles 698 à 700 de l'AUSCGIE ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_21',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Sommes-nous convaincus qu'il n'y a pas d'autres objections éthiques sur la base desquelles le cabinet n'accepterait pas le client ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_23',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous obtenu l'original ou l'expédition ou la copie certifiée conforme de l'extrait du RCCM attestant : "),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_24',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='a. La forme juridique ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_25',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='b.\tLe siège social ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_26',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='c.\tLes pouvoirs des personnes agissant au nom de la société ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_27',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Avons-nous obtenu les statuts à jour ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_28',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Connaissons-nous avec certitude l'adresse du client ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_29',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Avons-nous personnellement rencontré le client (face à face) ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_3',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="A-t-on connaissance de liens financiers entre, d'une part, la personne ou l'entité contrôlée ou l'une des personnes qui la contrôle ou est contrôlée par elle et, d'autre part, le signataire ou un membre de sa famille ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_30',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Avons-nous pu identifier les administrateurs au travers de la publication de leur nomination ainsi que des comptes annuels déposés ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_31',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous une copie de la pièce d'identité des administrateurs, gérants et directeurs de la société (document original, en cours de validité, avec photo et adresse dont nous prenons nous même une copie) ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_32',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous un document probant permettant de valider leur pouvoir d'engager la société ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_33',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Connaissons-nous l'identité de l'ayant droit économique ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_34',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="S'il s'agit d'une personne morale, avons-nous obtenu les documents d'identification énoncés au point 15 ci-dessus ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_35',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="S'il s'agit d'une personne physique, avons-nous obtenu une pièce d'identité, en cours de validité, avec photo, et adresse (original dont nous prenons nous même copie) ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_36',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous obtenu les justificatifs d'adresse ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_37',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous procédé à des vérifications complémentaires via des moteurs de recherche ou d'autres sources externes sur l'entité et ses dirigeants clés ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_38',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Le client est-il une PPE nationale ou étrangère ? (Si oui, Application des procédures spécifiques prévues par l'article 54 de la loi LBCFT)."),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_39',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Dans le cas d'une PPE étrangère avons-nous pu établir l'origine du patrimoine et l'origine des fonds impliqués dans la relation d'affaires ou la transaction ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_4',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Le cabinet ou ses associés ont-ils obtenu/accordé un emprunt, des avances de fonds ou des garanties?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_40',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="A-t-on procédé au background check tel qu'il est prévu dans le manuel ISQM du cabinet ? (Joindre les preuves)"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_41',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Des doutes ont-ils été soulevés concernant l'intégrité de l'entité, ses propriétaires, administrateurs, dirigeants ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_42',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="La réputation et l'image de l'entreprise et de l'organe de gestion sont-elles contestables ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_43',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Les recherches effectuées et les informations obtenues sur l'historique professionnel pertinent des administrateurs/gérants actuels sont-elles sources de préoccupation ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_44',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="La nature des activités du client, en ce compris la gestion d'entreprise, est-elle propice aux risques en matière d'intégrité ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_45',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Dispose-t-on d'informations portant à croire que le client participe au blanchiment d'argent, au financement du terrorisme, ou à d'autres activités criminelles, et notamment la provenance des fonds ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_46',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous relevé des sources de préoccupation dans les documents d'identification obtenus ou en raison de leur non obtention ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_47',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Décrivez succinctement les activités et les clients les plus importants de la société : ceux-ci constituent-ils un risque spécifique ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_48',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Le client intervient-il dans un secteur d'activité exposé à la fraude ou à des risques de blanchiment d'argent ou de financement du terrorisme ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_49',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Image médiatique du dirigeant et/ou de l'entreprise est-elle susceptible de nuire à l'image du cabinet ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_5',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Existe-t-il une participation financière détenue chez le client ou une entité qui la controle ou qui est contrôlée par elle par :  '),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_50',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Si notre nomination intervient dans le cadre d'un non renouvellement, d'une démission ou d'un empêchement, avons-nous pris contact avec le confrère précédent ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_51',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Les discussions avec le prédécesseur ont-elles révélé des risques sur les éléments suivants :'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_52',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="(a) L'accès aux dossiers du client ;"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_53',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='(b) Les honoraires impayés ;'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_54',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="(c) Les divergences d'opinions ou différends ;"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_55',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="(d) L'intégrité des dirigeants et du conseil ;"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_56',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='(e) Les raisons du changement ;'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_57',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='(f) Les exigences déraisonnables ou le manque de coopération ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_58',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='(g) Le non-respect des lois et réglementations ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_59',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='(h) Autres raisons pour lesquelles nous ne devrions pas accepter la mission.'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_6',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='a. Un associé du cabinet ou un membre de sa famille proche ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_60',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Les procédures légales de démission ou révocation ont-elles été respectées ? '),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_61',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Existe-t-il des problèmes de continuité à signaler ou à anticiper ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_62',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Les méthodes comptables utilisées dans le cadre de la préparation des états financiers sont-elles sources de préoccupation en termes d'adéquation et de permanence des méthodes ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_63',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Des risques fiscaux, sociaux, juridiques sont-ils liés à l'activité de la société ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_64',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="La direction n'est pas sensible aux recommandations ou n'a pas mis en place les recommandations de contrôle interne émises par les auditeurs internes et/ou externes."),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_65',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Le client est-il soumis à une réglementation particulière ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_66',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='La revue des rapports et dossiers des exercices précédents a-t-elle révélé '),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_67',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='a.\tDes réserves'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_68',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="b.\tD'autres anomalies significatives"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_69',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='c.\tDes problématiques comptables particulières ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_7',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='b. Le cabinet'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_70',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='La comptabilité semble-t-elle être mal tenue ou en retard ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_71',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Organisation déficiente pouvant entraîner des limitations aux travaux d'audit ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_72',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="La compétence ou l'expérience du personnel sont-elles un facteur de risques ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_73',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Incertitude sur l'exhaustivité des transactions du fait de l'activité, de l'organisation et/ou du dirigeant"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_74',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Avons-nous identifié des facteurs de risque de fraude concernant l'entité ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_75',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Si l'entité opère dans un secteur réglementé, avons-nous des difficultés pour obtenir les autorisations/agréments nécessaires ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_76',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='En cas de CO-CAC, avons-nous des doutes sur la capacité du COCAC à remplir ses obligations dans le respect des normes professionnelles ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_77',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Dans le cas de l'audit du groupe, notre Intervention est-elle limitée à certaines sociétés du groupe ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_78',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Y -a-t-il un risque que la direction de l'entité impose une limitation de l'étendue de l'audit ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_79',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Le client attend-il de nous des positions différentes de celles du prédécesseur ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_8',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='c. Un membre du réseau ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_80',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Avons-nous un doute sur notre capacité à réaliser la mission dans le délai défini ? '),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_81',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Avons-nous un doute sur notre capacité à mobiliser le personnel en nombre suffisant disposant des compétences et des connaissances requises pour effectuer la mission ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_82',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Le cas échéant, avons-nous un doute sur la disponibilité, la compétence et la réputation de l'expert devant intervenir sur la mission ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_83',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name='Le cas échéant, rencontrons-nous des difficultés pour identifier un réviseur indépendant ayant les compétences et la disponibilité requises pour remplir le rôle ?'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_9',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="d. Un membre de l'équipe de la mission ?"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='start_year',
            field=models.CharField(max_length=10, verbose_name="Si l'entité a moins de cinq ans, indiquer l'année de démarrage de l'activité"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='stock_exchange',
            field=models.CharField(max_length=255, verbose_name='Si entité cotée, bourse(s) de cotation'),
        ),
    ]
