# Generated by Django 5.2.7 on 2025-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_acceptationaudit_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
    ]
