# Generated by Django 5.2.7 on 2025-10-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_acceptationaudit_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_1',
            field=models.BooleanField(default=False, verbose_name='Étape 1'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_10',
            field=models.BooleanField(default=False, verbose_name='Étape 10'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_11',
            field=models.BooleanField(default=False, verbose_name='Étape 11'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_12',
            field=models.BooleanField(default=False, verbose_name='Étape 12'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_2',
            field=models.BooleanField(default=False, verbose_name='Étape 2'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_3',
            field=models.BooleanField(default=False, verbose_name='Étape 3'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_4',
            field=models.BooleanField(default=False, verbose_name='Étape 4'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_5',
            field=models.BooleanField(default=False, verbose_name='Étape 5'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_6',
            field=models.BooleanField(default=False, verbose_name='Étape 6'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_7',
            field=models.BooleanField(default=False, verbose_name='Étape 7'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_8',
            field=models.BooleanField(default=False, verbose_name='Étape 8'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_9',
            field=models.BooleanField(default=False, verbose_name='Étape 9'),
        ),
    ]
