# Generated by Django 5.2.7 on 2025-10-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_acceptationaudit_step_1_acceptationaudit_step_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptationaudit',
            name='step_13',
            field=models.BooleanField(default=False, verbose_name='Étape 13'),
        ),
    ]
