# Generated by Django 5.2.7 on 2025-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_acceptationaudit_step_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='cocac_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du co-CAC (si applicable)'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='component_audit_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du composant (si applicable)'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='has_cocac',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name="S'agit -il d'un Co-CAC ? Si oui indiquer le nom du co-CAC"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='independent_review_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la revue indépendante (si applicable)'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='is_component_audit',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non')], max_length=10, verbose_name="S'agit-il de l'audit d'un composant ? Si oui nom de l'auditeur du groupe"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='start_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Si l'entité a moins de cinq ans, indiquer l'année de démarrage de l'activité"),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Si entité cotée, bourse(s) de cotation'),
        ),
    ]
