# Generated by Django 5.2.7 on 2025-10-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_acceptationaudit_cocac_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='associate_signature',
        ),
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='collaborator_signature',
        ),
    ]
