# Generated by Django 5.2.7 on 2025-10-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_acceptationaudit_associate_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='cac_auditor',
            field=models.PositiveIntegerField(verbose_name='CAC/Auditeur'),
        ),
    ]
