# Generated by Django 5.2.7 on 2025-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_branche_cac_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptationaudit',
            name='accepte_mission',
            field=models.CharField(choices=[('', '--'), ('yes', 'Accepter la mission'), ('no', 'Refuser la mission')], default='', max_length=20, verbose_name='Accepté'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='conclusion_mission',
            field=models.TextField(blank=True, verbose_name='Conclusion de la mission'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='diligence_risk',
            field=models.CharField(choices=[('', '--'), ('normal', 'Vigilance normale'), ('enhanced', 'Vigilance renforcée')], default='', max_length=20, verbose_name='Vigilance de la diligence'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='global_risk',
            field=models.CharField(choices=[('', '--'), ('low', 'Risque faible'), ('medium', 'Risque modéré'), ('high', 'Risque élevé')], default='', max_length=20, verbose_name='Risque global'),
        ),
    ]
