# Generated by Django 5.2.7 on 2025-10-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_statut_profile_status'),
        ('core', '0012_acceptationaudit_accepte_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptationaudit',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Audit envoyé'),
        ),
    ]
