# Generated by Django 5.2.7 on 2025-10-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_acceptationaudit_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='departement',
        ),
    ]
