# Generated by Django 5.2.7 on 2025-10-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_acceptationaudit_accepte_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='reviewed_view_date',
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='signed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Le (signature)'),
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_audit_signed_by', to=settings.AUTH_USER_MODEL, verbose_name='Signé par'),
        ),
    ]
