# Generated by Django 5.2.7 on 2025-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_acceptationaudit_reviewed_view_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptationaudit',
            old_name='archived_view_date',
            new_name='signed_view_date',
        ),
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='acceptationaudit',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='acceptationaudit',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Signé'),
        ),
    ]
