# Generated by Django 5.2.7 on 2025-10-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_archived_view_date_acceptationaudit_signed_view_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='senior_signature',
            field=models.ImageField(blank=True, upload_to='signatures/', verbose_name='Signature senior'),
        ),
    ]
