# Generated by Django 5.2.7 on 2025-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_acceptationaudit_senior_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='senior_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature senior'),
        ),
    ]
