# Generated by Django 5.2.7 on 2025-10-29 19:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_acceptationaudit_senior_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='senior_signature',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.audit_signature_path, verbose_name='Signature senior'),
        ),
    ]
