# Generated by Django 5.2.3 on 2025-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_change_senior_signature_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='exercice',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], max_length=4, verbose_name='Exercice'),
        ),
        migrations.AlterField(
            model_name='acceptationaudit',
            name='question_19',
            field=models.CharField(choices=[('', '--'), ('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'N/A')], default='', max_length=20, verbose_name="Le cabinet, les membres du réseau (notamment le réseau Moore) ont-ils réalisé en faveur du client ou des entités qui la contrôle ou qu'elle contrôle, des prestations incompatibles avec le mandat de CAC ?"),
        ),
    ]
