# Generated by Django 5.2.3 on 2025-10-30 22:10

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_set_exercice_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nationalité'),
        ),
    ]
