# Generated by Django 5.2.7 on 2025-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_use_countryfield_for_branche_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptationaudit',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
    ]
